name: hello_world_csharp
on: [push]
jobs:
  hola-mundo:
    runs-on: windows-latest
    steps:
      #- name: Public IP
        #id: ip
        #uses: haythem/public-ip@v1.3
      - name: Checkout
        uses: actions/checkout@v3
      #- name: Define env variable
       # run: echo "UserName=${{ github.actor }}" >> $GITHUB_ENV
      - name: Hola Mundo Hello World correr Script
        run: dotnet run hello_world.cs
